---
services: docker

env:
  - distro: ubuntu1804
  - distro: ubuntu1604
    # - distro: ubuntu1404: does not build

script:
  # Configure test script so we can run extra tests after playbook is run.
  - export container_id=$(date +%s)
  - export cleanup=false

  # Download test shim.
  - wget -O ${PWD}/tests/test.sh https://gist.githubusercontent.com/leucos/b64ada597fa7281bab4620cd56f6fa46/raw/2dc8100bab92da745c7a7b38990df2a3546048d0/ansible-role-test.sh
  - chmod +x ${PWD}/tests/test.sh

  # Run tests.
  - ${PWD}/tests/test.sh

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
