- name: Adds few niceties
  apt:
    pkg: "{{ item }}"
    state: present
  with_items:
    - "{{ baseline_packages }}"
    - "{{ baseline_packages_addons }}"

- name: Changes TZ
  file:
    state: link
    src: "/usr/share/zoneinfo/{{ baseline_tz }}"
    dest: /etc/localtime
    force: yes
  tags: ["tz","baseline:tz"]
  notify:
    - Restart rsyslogd

- name: Creates required groups
  group:
    name: "{{ item.group | default(item.name) }}"
  with_items: "{{ baseline_users }}"

- name: Creates base users
  user:
    name: "{{ item.name }}"
    password: "{{ item.password | default(omit) }}"
    group: "{{ item.group | default(item.name) }}"
    groups: "{{ item.groups }}"
    append: yes
    shell: /bin/bash
    update_password: on_create
  with_items: "{{ baseline_users }}"

- name: Adds bash dotfile setup
  file:
    state: directory
    dest: "{{'~' + item.name }}/.bash.d/"
    mode: 0770
    owner: "{{ item.name }}"
    group: "{{ item.group | default(item.name) }}"
  with_flattened:
    - [ { name: 'root' } ]
    - [ "{{ baseline_users }}" ]

- name: Adds .bashrc
  template:
    src: bashrc.j2
    dest: "{{'~' + item.name }}/.bashrc"
    mode: 0770
    owner: "{{ item.name }}"
    group: "{{ item.group | default(item.name) }}"
  with_flattened:
    - [ { name: root } ]
    - [ "{{ baseline_users }}" ]

- name: Adds 10_prompt.bash
  template:
    src: 10_prompt.bash.j2
    dest: "{{'~' + item.name }}/.bash.d/10_prompt.bash"
    mode: 0770
    owner: "{{ item.name }}"
    group: "{{ item.group | default(item.name) }}"
  with_flattened:
    - [ { name: root } ]
    - [ "{{ baseline_users }}" ]

- name: Adds proper file limits
  template:
    src: limits-file.conf.j2
    dest: /etc/security/limits.d/filemax.conf

    #- name: Adds auto whitelisting profile script
    #  template:
    #    src: auto_whitelist.sh.j2
    #    dest: /etc/profile.d/auto_whitelist.sh
    #    mode: 0770
    #
