- name: Adds few niceties
  apt:
    pkg: "{{item}}"
    state: latest
  with_items:
    - "{{ baseline_packages }}"
    - "{{ baseline_packages_addons }}"

- name: Changes TZ
  file:
    state: link
    src: "/usr/share/zoneinfo/{{ baseline_tz }}"
    dest: /etc/localtime
  tags: tz

- name: Creates required groups
  group:
    name: "{{ item.group | default(item.name) }}"
  with_items: "{{ baseline_users }}"

- name: Creates base users
  user:
    name: "{{ item.name }}"
    group: "{{ item.group | default(item.name) }}"
    groups: "{{ item.group | default([item.name]) | intersect(item.groups | default([])) | join(',') }}"
    shell: /bin/bash
  with_items: "{{ baseline_users }}"

- name: Adds bash dotfile setup
  file:
    state: directory
    dest: "{{'~' + item.name }}/.bash.d/"
    mode: 0770
    owner: "{{ item.name }}"
    group: "{{ item.group | default(item.name) }}"
  with_flattened:
    - [ { name: 'root' } ]
    - [ "{{ baseline_users }}" ]

- name: Adds .bashrc
  template:
    src: bashrc.j2
    dest: "{{'~' + item.name }}/.bashrc"
    mode: 0770
    owner: "{{ item.name }}"
    group: "{{ item.group | default(item.name) }}"
  with_flattened:
    - [ { name: root } ]
    - [ "{{ baseline_users }}" ]

- name: Adds 10_prompt.bash
  template:
    src: 10_prompt.bash.j2
    dest: "{{'~' + item.name }}/.bash.d/10_prompt.bash"
    mode: 0770
    owner: "{{ item.name }}"
    group: "{{ item.group | default(item.name) }}"
  with_flattened:
    - [ { name: root } ]
    - [ "{{ baseline_users }}" ]

- name: Adds proper file limits
  template:
    src: limits-file.conf.j2
    dest: /etc/security/limits.d/filemax.conf

