- name: Install System Packages
  apt:
    pkg: "{{ item }}"
    state: present
  with_items: "{{ uu_system_packages }}"

- name: Place unattended upgrades config files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0600
  with_items:
    - { src: uu_config.j2, dest: /etc/apt/apt.conf.d/50unattended-upgrades }
    - { src: uu_periodic.j2, dest: /etc/apt/apt.conf.d/02periodic }

